### ISSUE TITLE
Remove default margin beetwen fragment container

### ISSUE THREAD

**Issue by webserveis** [ohmae/preference-activity-compat#2]
I see that there is a margin of the fragment with elements, if you want you can eliminate it with

```java
    private static abstract class CustomPreferenceFragmentCompat extends PreferenceFragmentCompat {

        //Remove margin fragment
        @Override
        public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
            super.onViewCreated(view, savedInstanceState);
            View containerParent = (View)view.getParent();
            containerParent.setPadding(0, 0, 0, 0);
        }
```

**Comment by ohmae** [comment]
Thanks. However, I do not want it.
preference-v7 is doing extra things, so it's hard to use. :sweat:
This project is not aimed at improving preference-v7 itself. 
I think that it is the role of other projects such as the project you taught me. :+1:
