### ISSUE TITLE
Remove space reservated for icon app:iconSpaceReserved

### ISSUE THREAD

**Issue by webserveis** [ohmae/preference-activity-compat#3]
I found an official alternative to eliminate the space. Reserved for the icon

`app:iconSpaceReserved`

sample
```
    <Preference
        android:key="pref_send_feedback"
        app:iconSpaceReserved="false"
        android:title="@string/pref_about_send_feedback_title" />

```

Extract from
https://stackoverflow.com/questions/18509369/android-how-to-get-remove-margin-padding-in-preference-screen

**Comment by ohmae** [comment]
Awesome!! Thank you for your information.
I tried using it immediately. https://github.com/ohmae/preference-activity-compat/commit/61041a542b19ef19394176982c04f8883f9f4e2e
