### ISSUE TITLE
How do I implement onMenuItemSelected?

### ISSUE THREAD

**Issue by CliffCawley** [ohmae/preference-activity-compat#4]
If you create a SettingsActivity with the wizard, it creates:
```
    @Override
    public boolean onMenuItemSelected(int featureId, MenuItem item)
    {
        int id = item.getItemId();
        if (id == android.R.id.home)
        {
            if (!super.onMenuItemSelected(featureId, item))
            {
                NavUtils.navigateUpFromSameTask(this);
            }
            return true;
        }
        return super.onMenuItemSelected(featureId, item);
    }
```

This isn't available to override when using your control and without it, tapping the back button causes some odd behaviour and eventually a crash due to missing controls.

Is it possible to still allow this to be overridden or a work around?

**Comment by ohmae** [comment]
I tried to create SettingActivity using wizard.
![2018-12-21](https://user-images.githubusercontent.com/7691979/50321292-8c6d4680-0513-11e9-9b97-b469672f8861.png)
but there was no such method... :thinking: 

So I cannot know what your code is like.
`onMenuItemSelected` is final method in AppCompatActivity.
https://developer.android.com/reference/androidx/appcompat/app/AppCompatActivity#onMenuItemSelected(int,%20android.view.MenuItem)
Please try to override `onOptionsItemSelected`
https://developer.android.com/reference/android/app/Activity#onOptionsItemSelected(android.view.MenuItem)

**Comment by ohmae** [comment]
I found it!
It was necessary to specify "Hierarchical Parent" :sweat_smile: 
![2018-12-21 1](https://user-images.githubusercontent.com/7691979/50322593-0653fe80-0519-11e9-959f-e3c318bcc57c.png)

Please change as follows.
```java
    @Override
    public boolean onOptionsItemSelected(final MenuItem item) {
        final int id = item.getItemId();
        if (id == android.R.id.home) {
            if (!super.onOptionsItemSelected(item)) {
                NavUtils.navigateUpFromSameTask(this);
            }
            return true;
        }
        return super.onOptionsItemSelected(item);
    }
```

**Comment by ohmae** [comment]
I updated readme https://github.com/ohmae/preference-activity-compat/commit/7f241ed0546bdb386bbdc4f11ca0e3c4f792a895

**Comment by CliffCawley** [comment]
Awesome, thank you!! 👍
