### ISSUE TITLE
Incompatible with v1.1.0-rc01 of androidx.preference:preference

### ISSUE THREAD

**Issue by 1951FDG** [ohmae/preference-activity-compat#5]
Latest compatible version is 1.1.0-alpha03, would be great if it could work with 1.1.0-rc01

**Android resource linking failed**

`mm2d_pac_content.xml:28: error: resource attr/preferenceListStyle (aka io.github.getsixtyfour.openpyn:attr/preferenceListStyle) not found.`

`mm2d_pac_content.xml:53: error: resource attr/preferencePanelStyle (aka io.github.getsixtyfour.openpyn:attr/preferencePanelStyle) not found.`

**Comment by ohmae** [comment]
Thanks for the report. I'll try to fix it.

**Comment by 1951FDG** [comment]
Great! Thanks!

**Comment by ohmae** [comment]
fixed https://github.com/ohmae/preference-activity-compat/commit/59184e198bba8bff4ef9b500d7cd3223f61d2bb7
