### ISSUE TITLE
Add EXTRA_NO_HEADERS, EXTRA_SHOW_FRAGMENT functionality

### ISSUE THREAD

**Issue by 1951FDG** [ohmae/preference-activity-compat#6]
Hi,

Great work, while revising the code I noticed that you chose to not include the EXTRA_NO_HEADERS, EXTRA_SHOW_FRAGMENT functionality, would you consider including it in the future?

**Comment by ohmae** [comment]
Ok. I'll consider adding that feature

**Comment by 1951FDG** [comment]
Thanks, appreciate it!

**Comment by ohmae** [comment]
Done https://github.com/ohmae/preference-activity-compat/commit/05079726ee537057ff96fe42636b27011210be51
