### ISSUE TITLE
Signature changed for method

### ISSUE THREAD

**Issue by 1951FDG** [ohmae/preference-activity-compat#7]
Hi,

Thanks for the changes made! I did notice however that the signature changed of:

```
**from:**
override fun onBuildHeaders(target: List<Header>)
**to:**
override fun onBuildHeaders(target: MutableList<Header>)
```

**Comment by ohmae** [comment]
Yes,  Because I convert to Kotlin.
It should be MutableList originally.
I will update readme

**Comment by ohmae** [comment]
done https://github.com/ohmae/preference-activity-compat/commit/e1ca3cb7b2542d1c560557d3c0d8d5f5ab29dd09

**Comment by 1951FDG** [comment]
understood, thx again!
